### ISSUE TITLE
"Send (Main Webhook)" not working & throwing an error

### ISSUE THREAD

**Issue by chaoscontrolled123** [therealguy90/foundrytodiscord#50]
**Describe the bug**
Message are sending when the GM is logged in, but right-clicking a message to send to the main webhook is not.

**To Reproduce**
1. Go to any message
2. Click on "Send (Main Webhook)"
3. Nothing appears in Discord
4. Strange error in console (see screenshot)

**Expected behavior**
Message should be sent to Discord webhook channel.

**Screenshots**

<img width="1032" height="184" alt="Image" src="https://github.com/user-attachments/assets/ed6e446e-4521-4aa8-813c-94c11e138849" />

**Additional context**
Not sure how long this has been a problem-- this is the first time I've tried to use this function, since I forgot to enable sending messages when the GM was offline. Great work on this module, we use it with CAIN and it works perfectly otherwise!

**Comment by therealguy90** [comment]
Are you running on v12 or v13?

**Comment by therealguy90** [comment]
Should be fixed in 7bffbf5125b54054b775b2f66c06495909ab3954, so if you grab the source code zip and put it in your modules folder, it should work. In a few days, I'll make a new release if this is confirmed to be working.

**Comment by therealguy90** [comment]
There, 4323fae3d166f12ea32b6d86e8f19a94391ca70e should fix this.

**Comment by chaoscontrolled123** [comment]
Sorry for the delay on getting back to you! I wanted to try again on my home computer to be sure. I'm still seeing the same error, in both Firefox and Vivaldi:

<img width="498" height="110" alt="Image" src="https://github.com/user-attachments/assets/a058b3bd-1853-479f-a576-324bd78d2b6b" />

My code reading is rusty but the inspector is showing the new code from the latest commit. I guess it's throwing the error before it even gets to the compatibility fix?

**Comment by therealguy90** [comment]
Hmm, yeah, that's odd. Guess I'll have to make the code a little longer. 164590cb73399aa2cf31bcb83c0a123f3f127ff2 should work...
